---
# tasks file for certbot-cloudflare

- name: Get software for apt repository management.
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - libffi-dev
    - libssl-dev
    - python-apt
    - python-dev
    - python-pycurl
    - s3cmd

- name: Install pip
  include_role:
    name: geerlingguy.pip

- name: Install Certbot without Domains.
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_certs: []

- name: check if certbot-dns-cloudflare plugin is installed
  shell: certbot plugins | grep dns-cloudflare
  register: cf_check
  ignore_errors: true
  changed_when: "cf_check is failed"

- name: Install certbot-dns-cloudflare
  shell: "cd {{certbot_dir}}/certbot-dns-cloudflare && python setup.py install"
  when: cf_check is failed
- name: Create certbot folder - sudouser
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0700
- name: Certbot Template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'templates/confcloudflare.ini.j2', dest: '/etc/letsencrypt/dnscloudflare.ini' }
    - { src: 'templates/letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini' }

- name: Create Certs.
  include_role:
    name: geerlingguy.certbot